# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_projectPanel.ui'
#
# Created: Wed Mar 08 17:31:40 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_projectPanel(object):
    def setupUi(self, projectPanel):
        projectPanel.setObjectName("projectPanel")
        projectPanel.resize(1005, 670)
        self.verticalLayout_5 = QtGui.QVBoxLayout(projectPanel)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(projectPanel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(projectPanel)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.category_comb = QtGui.QComboBox(projectPanel)
        self.category_comb.setMaximumSize(QtCore.QSize(125, 16777215))
        self.category_comb.setObjectName("category_comb")
        self.category_comb.addItem("")
        self.category_comb.addItem("")
        self.category_comb.addItem("")
        self.category_comb.addItem("")
        self.category_comb.addItem("")
        self.category_comb.addItem("")
        self.horizontalLayout_2.addWidget(self.category_comb)
        self.creat_btn = QtGui.QPushButton(projectPanel)
        self.creat_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.creat_btn.setSizeIncrement(QtCore.QSize(0, 0))
        self.creat_btn.setBaseSize(QtCore.QSize(0, 0))
        self.creat_btn.setObjectName("creat_btn")
        self.horizontalLayout_2.addWidget(self.creat_btn)
        self.import_btn = QtGui.QPushButton(projectPanel)
        self.import_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.import_btn.setObjectName("import_btn")
        self.horizontalLayout_2.addWidget(self.import_btn)
        self.open_btn = QtGui.QPushButton(projectPanel)
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout_2.addWidget(self.open_btn)
        self.open_dir_btn = QtGui.QPushButton(projectPanel)
        self.open_dir_btn.setObjectName("open_dir_btn")
        self.horizontalLayout_2.addWidget(self.open_dir_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.splitter = QtGui.QSplitter(projectPanel)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.project_list = QtGui.QListWidget(self.layoutWidget)
        self.project_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.project_list.setObjectName("project_list")
        self.verticalLayout.addWidget(self.project_list)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.scene_list = QtGui.QListWidget(self.layoutWidget1)
        self.scene_list.setObjectName("scene_list")
        self.verticalLayout_2.addWidget(self.scene_list)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.shot_list = QtGui.QListWidget(self.layoutWidget2)
        self.shot_list.setObjectName("shot_list")
        self.verticalLayout_3.addWidget(self.shot_list)
        self.layoutWidget3 = QtGui.QWidget(self.splitter)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.file_list = QtGui.QListWidget(self.layoutWidget3)
        self.file_list.setObjectName("file_list")
        self.verticalLayout_4.addWidget(self.file_list)
        self.verticalLayout_5.addWidget(self.splitter)
        self.verticalLayout_5.setStretch(2, 7)

        self.retranslateUi(projectPanel)
        QtCore.QMetaObject.connectSlotsByName(projectPanel)

    def retranslateUi(self, projectPanel):
        projectPanel.setWindowTitle(QtGui.QApplication.translate("projectPanel", "Project Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("projectPanel", " Path: ", None, QtGui.QApplication.UnicodeUTF8))
        self.category_comb.setItemText(0, QtGui.QApplication.translate("projectPanel", "comp", None, QtGui.QApplication.UnicodeUTF8))
        self.category_comb.setItemText(1, QtGui.QApplication.translate("projectPanel", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.category_comb.setItemText(2, QtGui.QApplication.translate("projectPanel", "paint", None, QtGui.QApplication.UnicodeUTF8))
        self.category_comb.setItemText(3, QtGui.QApplication.translate("projectPanel", "roto", None, QtGui.QApplication.UnicodeUTF8))
        self.category_comb.setItemText(4, QtGui.QApplication.translate("projectPanel", "percomp", None, QtGui.QApplication.UnicodeUTF8))
        self.category_comb.setItemText(5, QtGui.QApplication.translate("projectPanel", "denoise", None, QtGui.QApplication.UnicodeUTF8))
        self.creat_btn.setText(QtGui.QApplication.translate("projectPanel", "Creat", None, QtGui.QApplication.UnicodeUTF8))
        self.import_btn.setText(QtGui.QApplication.translate("projectPanel", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.open_btn.setText(QtGui.QApplication.translate("projectPanel", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.open_dir_btn.setText(QtGui.QApplication.translate("projectPanel", "OpenDir", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("projectPanel", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("projectPanel", "Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("projectPanel", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("projectPanel", "File", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    projectPanel = QtGui.QDialog()
    ui = Ui_projectPanel()
    ui.setupUi(projectPanel)
    projectPanel.show()
    sys.exit(app.exec_())

